### ISSUE TITLE
org-ql-find: intermittent freezing with vertico

### ISSUE THREAD

**Issue by anpandey** [alphapapa/org-ql#350] opened 2023-04-26 06:37 UTC
When using 0.7.1-pre's `org-ql-find` with vertico, I sometimes get the following message:

```
Error in post-command-hook (vertico--exhibit): (user-error "Before first headline at position 13 in buffer  *Minibuf-1*")
```

follwed by completion freezing up until it's manually cancelled. There doesn't appear to be a specific query causing it, and the only semi-reliable way I was to reproduce this was by changing the query randomly (and quickly) until I got the error. I was also able to reproduce this in a minimal (4-headline) file, manual debug trace below (it seems like a nil marker causes org-back-to-heading to be called within the minibuffer):

```
Debugger entered: nil
  (or (re-search-backward (concat "^\\(?:" outline-regexp "\\)") nil t) (debug) (user-error "Before first headline at position %d in buffer %s" (point) (current-buffer)))
  (while (not found) (or (re-search-backward (concat "^\\(?:" outline-regexp "\\)") nil t) (debug) (user-error "Before first headline at position %d in buffer %s" (point) (current-buffer))) (if (and (featurep 'org-inlinetask) (fboundp 'org-inlinetask-end-p) (org-inlinetask-end-p)) (org-inlinetask-goto-beginning) (setq found (and (or invisible-ok (not (org-fold-folded-p))) (point)))))
  (save-excursion (if (and (featurep 'org-inlinetask) (fboundp 'org-inlinetask-end-p) (org-inlinetask-end-p)) (progn (goto-char (line-beginning-position)))) (while (not found) (or (re-search-backward (concat "^\\(?:" outline-regexp "\\)") nil t) (debug) (user-error "Before first headline at position %d in buffer %s" (point) (current-buffer))) (if (and (featurep 'org-inlinetask) (fboundp 'org-inlinetask-end-p) (org-inlinetask-end-p)) (org-inlinetask-goto-beginning) (setq found (and (or invisible-ok (not (org-fold-folded-p))) (point))))))
  (let (found) (save-excursion (if (and (featurep 'org-inlinetask) (fboundp 'org-inlinetask-end-p) (org-inlinetask-end-p)) (progn (goto-char (line-beginning-position)))) (while (not found) (or (re-search-backward (concat "^\\(?:" outline-regexp "\\)") nil t) (debug) (user-error "Before first headline at position %d in buffer %s" (point) (current-buffer))) (if (and (featurep 'org-inlinetask) (fboundp 'org-inlinetask-end-p) (org-inlinetask-end-p)) (org-inlinetask-goto-beginning) (setq found (and (or invisible-ok (not ...)) (point)))))) (goto-char found) found)
  (if (org-element--cache-active-p) (let ((heading (org-element-lineage (org-element-at-point) '(headline inlinetask) 'include-self))) (if heading (progn (goto-char (org-element-property :begin heading)))) (while (and (not invisible-ok) heading (org-fold-folded-p)) (goto-char (org-fold-core-previous-visibility-change)) (setq heading (org-element-lineage (org-element-at-point) '(headline inlinetask) 'include-self)) (if heading (progn (goto-char (org-element-property :begin heading))))) (if heading nil (debug) (user-error "Before first headline at position %d in buffer %s" (point) (current-buffer))) (point)) (let (found) (save-excursion (if (and (featurep 'org-inlinetask) (fboundp 'org-inlinetask-end-p) (org-inlinetask-end-p)) (progn (goto-char (line-beginning-position)))) (while (not found) (or (re-search-backward (concat "^\\(?:" outline-regexp "\\)") nil t) (debug) (user-error "Before first headline at position %d in buffer %s" (point) (current-buffer))) (if (and (featurep 'org-inlinetask) (fboundp 'org-inlinetask-end-p) (org-inlinetask-end-p)) (org-inlinetask-goto-beginning) (setq found (and (or invisible-ok ...) (point)))))) (goto-char found) found))
  (or (and (org-at-heading-p (not invisible-ok)) (not (and (featurep 'org-inlinetask) (fboundp 'org-inlinetask-end-p) (org-inlinetask-end-p)))) (if (org-element--cache-active-p) (let ((heading (org-element-lineage (org-element-at-point) '(headline inlinetask) 'include-self))) (if heading (progn (goto-char (org-element-property :begin heading)))) (while (and (not invisible-ok) heading (org-fold-folded-p)) (goto-char (org-fold-core-previous-visibility-change)) (setq heading (org-element-lineage (org-element-at-point) '(headline inlinetask) 'include-self)) (if heading (progn (goto-char (org-element-property :begin heading))))) (if heading nil (debug) (user-error "Before first headline at position %d in buffer %s" (point) (current-buffer))) (point)) (let (found) (save-excursion (if (and (featurep 'org-inlinetask) (fboundp 'org-inlinetask-end-p) (org-inlinetask-end-p)) (progn (goto-char (line-beginning-position)))) (while (not found) (or (re-search-backward (concat "^\\(?:" outline-regexp "\\)") nil t) (debug) (user-error "Before first headline at position %d in buffer %s" (point) (current-buffer))) (if (and (featurep ...) (fboundp ...) (org-inlinetask-end-p)) (org-inlinetask-goto-beginning) (setq found (and ... ...))))) (goto-char found) found)))
  org-back-to-heading(t)
  org-up-heading-safe()
  org-get-outline-path(nil t)
  #f(compiled-function (marker) #<bytecode 0x93f5ad3be78f3fa>)(nil)
  #f(compiled-function (completions) #<bytecode 0x17cd8a122f0e5d5>)((#("indented headline" 0 17 (line-prefix #("**" 0 2 (face org-indent)) wrap-prefix #("***** " 0 6 (face org-indent)) fontified t face org-level-3)) #("This is another test, I don't know" 0 34 (line-prefix "" wrap-prefix #("* " 0 2 (face org-indent)) fontified t face org-level-1))))
  vertico--affixate((#("indented headline" 0 17 (line-prefix #("**" 0 2 (face org-indent)) wrap-prefix #("***** " 0 6 (face org-indent)) fontified t face org-level-3)) #("This is another test, I don't know" 0 34 (line-prefix "" wrap-prefix #("* " 0 2 (face org-indent)) fontified t face org-level-1))))
  vertico--arrange-candidates()
  vertico--exhibit()
  #<subr completing-read-default>("Find entry: " #f(compiled-function (input pred flag) #<bytecode 0x5410b96d6237eee>) nil t nil nil nil nil)
  apply((#<subr completing-read-default> "Find entry: " #f(compiled-function (input pred flag) #<bytecode 0x5410b96d6237eee>) nil t nil nil nil nil))
  vertico--advice(#<subr completing-read-default> "Find entry: " #f(compiled-function (input pred flag) #<bytecode 0x5410b96d6237eee>) nil t nil nil nil nil)
  apply(vertico--advice #<subr completing-read-default> ("Find entry: " #f(compiled-function (input pred flag) #<bytecode 0x5410b96d6237eee>) nil t nil nil nil nil))
  completing-read-default("Find entry: " #f(compiled-function (input pred flag) #<bytecode 0x5410b96d6237eee>) nil t nil nil nil nil)
  org-ql-completing-read(#<buffer testfile.org> :query-prefix nil :query-filter nil :prompt "Find entry: ")
  org-ql-find(#<buffer testfile.org>)
```

**Comment by alphapapa** [comment] 2023-04-26 18:16
Hello Ankit,

Thanks for reporting this problem, but I'm unable to reproduce it in a clean Emacs configuration using Emacs 28.2, Org 9.5.5, and the latest versions of `org-ql`, `vertico`, and all of their dependencies.  I used this test Org file:
```org
Before heading text.

* A
* B
* C
* D
```
And I tried various queries that I would expect to possibly cause the problem, including plain queries like `A`, `B`, and `h:A`, `todo:`, etc.

If you can still reproduce it, please try to do so in a clean configuration and recent versions of relevant packages, e.g. using https://github.com/alphapapa/with-emacs.sh.  If it still happens, please provide the versions of all the software you're using.

**Comment by WorldsEndless** [comment] 2023-05-19 14:22
I'm getting a similar problem. In particular, if I use backspace to change my  query interactively, the completion often ceases to update. In my error buffer I see this:

> Error in post-command-hook (vertico--exhibit): (user-error "Before first headline at position 13 in buffer  *Minibuf-1*")

I have updated my vertico to the latest version, and only just installed org-ql. I am on emacs 28.2 .

**Comment by alphapapa** [comment] 2023-05-19 14:55
@WorldsEndless That error is strange; it would seem to suggest that org-ql were trying to search the minibuffer's contents.  If you would, please provide complete, step-by-step instructions to reproduce that behavior, and I'll see if I can reproduce it.

**Comment by alphapapa** [comment] 2023-05-19 17:17
@WorldsEndless Thanks, I'll see what I can find.

**Comment by danielfleischer** [comment] 2023-05-21 18:57
I am able to reproduce; the issue goes away when I remove "orderless" from the completion styles, leave only "basic". I assume OP and others also use orderless since it's ofter used with vertico. Probably orderless fuzzyness doesn't play nice with the completion snippets which can be long and things explode. Now I just need to understand how to disable orderless when using org-ql queries.

**Comment by anpandey** [comment] 2023-05-25 11:51
I was still able to reproduce this even with orderless disabled. I double-checked to make sure that `(featurep 'orderless)` was nil.

**Comment by alphapapa** [comment] 2023-05-25 16:59
I can confirm that a bug exists that causes this error:

```
Error in post-command-hook (vertico--exhibit): (user-error "Before first headline at position 13 in buffer Minibuf-1")
```
I haven't found a way to reproduce it on-demand, specifically, but it seems that changing the search input, backspacing, adding and removing whitespace, etc. generally causes it within a few moments.

Unfortunately, I haven't found a way to see the backtrace, because its being in a completion command and using the minibuffer seems to prevent the backtrace from being displayed.  Even when I preemptively show the `*Backtrace*` buffer in another window before calling `org-ql-find`, it doesn't show the backtrace when the error is signaled (and `debug-on-error` is t, of course).

Without a backtrace, it's hard to say where the bug lies.  It seems that some of the code in `org-ql-completing-read` (and/or associated functions like `org-ql-find`) is being called inside the minibuffer rather than one of the Org buffers that is expected.  I'm guessing it's some of the code that annotates/affixes/etc. a candidate by switching to the candidate's buffer and moving to its marker.  This might be because some code in `org-ql` isn't using `org-with-point-at` where it should (which seems unlikely, given that it seems to work correctly before this error happens), or it might be something in `vertico--exhibit`' or the other functions it calls that's doing something unexpected with setting the current buffer.

It may take some time to debug this, and I don't know that I'll have much to spend on this problem soon.  I wonder if one of the Vertico maintainers could advise about an easier way to trace errors that occur during completion, since it seems to obscure the backtrace.

**Comment by alphapapa** [comment] 2023-05-25 17:02
@minad Daniel, if I may, do you have any advice about how to debug errors that happen during completion, since it seems impossible to get the backtrace?  Please note, I'm not asking you to debug this issue for me.  :)

**Comment by alphapapa** [comment] 2023-05-25 20:03
> > It seems that some of the code in org-ql-completing-read (and/or associated functions like org-ql-find) is being called inside the minibuffer rather than one of the Org buffers that is expected.
> 
> Yes, all the completion table functions are called inside the minibuffer (the completion table itself, annotation functions, etc). I recommend that you switch to the original buffer inside the completion table lambda.

Indeed, that should already be happening, and it seems to be working, until the error happens.
> 
> > do you have any advice about how to debug errors that happen during completion, since it seems impossible to get the backtrace?
> 
> The problem is that the Elisp debugger doesn't run inside post command hooks, since this makes Emacs somewhat dysfunctional. But you can opt-in explicitly, see https://github.com/minad/vertico#debugging-vertico. This way you should be able to obtain a stack trace.

*facepalm*  I had just looked at the Vertico readme before asking you, but somehow I overlooked that section.  Thank you.

**Comment by minad** [comment] 2023-05-26 10:37
I am not sure, but the issue could be caused by Vertico interrupting the completion table. Vertico and Icomplete rely on `while-no-input` to stay responsive. It could be that org-ql or Org manipulates some internal state in its dynamic completion table, which then gets corrupted due the unexpected interrupt. Such problems are rare since completion tables are usually only performing pure computations. If interruption is indeed the problem, you could let-bind `throw-on-input` to nil locally around a "critical section" where the uninterruptible state manipulation is taking place. As a first step, let-bind 'throw-on-input` to nil around everything. Of course this will hurt responsiveness, but then you could gradually restrict the scope of the critical section.

**Comment by alphapapa** [comment] 2023-05-26 14:05
@minad Thank you, that's exactly the kind of pointer I could use, since you know so much more about how Emacs completion works.  :)

**Comment by anpandey** [comment] 2023-06-15 04:16
Looking at this again a bit more, I couldn't reproduce it with Emacs 28 and these package versions using a minimal config file that only enables vertico:

```
vertico                        0.28
org-ql                         20221007.2334
org-super-agenda               20220826.2315
```

but I could with Emacs 29 and these versions:

```
vertico                        1.3
org-ql                         20230525.1548
org-super-agenda               20220826.2315
```

I'll try to narrow it down some more.

**Comment by bram85** [comment] 2023-06-15 05:03
Not sure if it helps, but I find it's easier to reproduce this issue on larger-than-average org-mode buffers, e.g. finding a single word in the Shakespeare.org file.

https://github.com/jdtsmith/shakespeare.org

**Comment by anpandey** [comment] 2023-06-16 09:58
Ok, I was able to isolate it to just org-ql, somewhere between `6257ae83044aa9fcd5c2ddffbd2f73f2b235f905` and `eb5377320fcfd38354d6e9e3e655969ae3c0e052`. Will try bisecting.

@bram85 Thanks, that makes it easier to reliably reproduce.

**Comment by anpandey** [comment] 2023-06-16 23:52
Seems like https://github.com/alphapapa/org-ql/commit/4c1a4b169f54d37ce541902c0ae5043759ef9d9b is the bad commit:

```
git bisect start 'eb5377320fcfd38354d6e9e3e655969ae3c0e052' '6257ae83044aa9fcd5c2ddffbd2f73f2b235f905'
eb53773 bad Comment: Add FIXME
6257ae8 good Fix: (org-ql-find--snippet-*) Use save-excursion

git bisect good 2ae60f8dc50cf2a156a3ca7ec929d19909139097
2ae60f8 good Tests: (src) More normal forms

git bisect good 1ae2f0cd60974e85b204cd1bd255aa39b253473f
1ae2f0c good Update the docstring

git bisect good 107fc66d08ea7afbe150a9b76a607b3a5981b383
107fc66 good Change: (org-ql-view--format-element) Use display-warning

git bisect good e08de2a76c2bbd6364126653fdd911b37243f572
e08de2a good Fix: (org-ql-completing-read) Bind org-outline-path-cache nil

git bisect bad 1d98c7d07c6f2af5c84e8358cb6c5db71e8f1006
1d98c7d bad Tests: Disable Org link bracket tests on old Org versions

git bisect bad 4c1a4b169f54d37ce541902c0ae5043759ef9d9b
```

**Comment by alphapapa** [comment] 2023-06-17 01:38
> Seems like [4c1a4b1](https://github.com/alphapapa/org-ql/commit/4c1a4b169f54d37ce541902c0ae5043759ef9d9b) is the bad commit:

Well, thanks, but as you can see, a lot of the code changed in that commit, and it was made to fix another bug.

I think the next step is to follow minad's advice.

**Comment by anpandey** [comment] 2023-06-20 18:36
It seems like the metadata functions in `org-ql-completing-read` get passed an older list of collections even though a new query that updated the hash table was already run. This means the metadata functions get passed a `nil` marker, so they end up executing the org-mode functions in the completion buffer. This aligns with [4c1a4b1](https://github.com/alphapapa/org-ql/commit/4c1a4b169f54d37ce541902c0ae5043759ef9d9b) which added clearing the hashtable for each query run.

Just protecting the hashtable lookup fixes the freezing, but now we occasionally end up with missing info in the completions:

<details>
<summary>Patch</summary>

```diff
diff --git a/org-ql-completing-read.el b/org-ql-completing-read.el
index 7d335b3..f361915 100644
--- a/org-ql-completing-read.el
+++ b/org-ql-completing-read.el
@@ -125,18 +125,22 @@ single predicate)."
                        (setf heading (format "%s <%s>" heading (puthash heading 2 disambiguations)))))
                    (puthash heading (point-marker) table)))
                 (path (marker)
-                      (org-with-point-at marker
-                        (let* ((path (thread-first (org-get-outline-path nil t)
-                                                   (org-format-outline-path window-width nil "")
-                                                   (org-split-string "")))
-                               (formatted-path (if org-ql-completing-read-reverse-paths
-                                                   (concat "\\" (string-join (reverse path) "\\"))
-                                                 (concat "/" (string-join path "/")))))
-                          formatted-path)))
+                      (if marker
+                       (org-with-point-at marker
+                         (let* ((path (thread-first (org-get-outline-path nil t)
+                                                    (org-format-outline-path window-width nil "")
+                                                    (org-split-string "")))
+                                (formatted-path (if org-ql-completing-read-reverse-paths
+                                                    (concat "\\" (string-join (reverse path) "\\"))
+                                                  (concat "/" (string-join path "/")))))
+                           formatted-path))
+                       "MISSING INFO"))
                 (todo
-                 (marker) (if-let (it (org-entry-get marker "TODO"))
-                              (concat (propertize it 'face (org-get-todo-face it)) " ")
-                            ""))
+                 (marker) (if marker
+                           (if-let (it (org-entry-get marker "TODO"))
+                               (concat (propertize it 'face (org-get-todo-face it)) " ")
+                             "")
+                           "MISSING INFO"))
                 (affix (completions)
                        ;; (debug-message "AFFIX:%S" completions)
                        (cl-loop for completion in completions
@@ -152,16 +156,21 @@ single predicate)."
                             ;; org-rifle-style snippets.
                             (or (snippet (gethash candidate table)) "")))
                 (snippet
-                 (marker) (when-let
-                              ((snippet
-                                (org-with-point-at marker
-                                  (or (funcall org-ql-completing-read-snippet-function snippet-regexp)
-                                      (org-ql-completing-read--snippet-simple)))))
-                            (propertize (concat " " snippet)
-                                        'face 'org-ql-completing-read-snippet)))
+                 (marker) (if marker
+                           (when-let
+                               ((snippet
+                                 (org-with-point-at marker
+                                   (or (funcall org-ql-completing-read-snippet-function snippet-regexp)
+                                       (org-ql-completing-read--snippet-simple)))))
+                             (propertize (concat " " snippet)
+                                         'face 'org-ql-completing-read-snippet))
+                           "MISSING INFO"))
                 (group (candidate transform)
                        (pcase transform
-                         (`nil (buffer-name (marker-buffer (gethash candidate table))))
+                         (`nil (let ((marker (gethash candidate table)))
+                                (if marker
+                                 (buffer-name (marker-buffer (gethash candidate table)))
+                                 "MISSING INFO")))
                          (_ candidate)))
                 (try (string _collection _pred point &optional _metadata)
                      ;; (debug-message "TRY: STRING:%S" string)
```
</details>

**Comment by alphapapa** [comment] 2023-06-20 20:32
@anpandey Thanks, that's very helpful.

**Comment by minad** [comment] 2023-06-20 21:03
I suggest you attach metadata directly to the candidates via text properties (annotations, grouping etc). Then such problems cannot occur. Of course this only works if the metadata is already readily available. In some cases it may not, e.g. my Marginalia package computes the costly annotation on demand only for the visible candidates.

**Comment by oantolin** [comment] 2023-06-25 00:23
Attaching the marker as a text property also enables easy Embark integration (well, that change plus giving the completion table a category metadatum).

**Comment by Ypot** [comment] 2023-08-20 19:25
Would you recommend an alternative to vertico, till this issue is solved?

**Comment by WorldsEndless** [comment] 2023-08-21 04:08
Alphapapa is a Helm man, if I'm not mistaken ☺

**Comment by alphapapa** [comment] 2023-09-06 21:10
Thanks to all for helping, and for your patience!

**Closed** 2023-09-06 21:10 UTC
Labels: bug

**Comment by chasecaleb** [comment] 2023-09-06 21:53
Tested and confirmed that this is fixed now. Thanks!

**Comment by alphapapa** [comment] 2023-09-06 23:46
@chasecaleb Thank you!
