### ISSUE TITLE
Unable to use org-ql anymore: Symbol’s function definition is void: with-peg-rules

### ISSUE THREAD

**Issue by falematte** [alphapapa/org-ql#199] opened 2021-03-04 15:56 UTC
After a Melpa update I started getting this error whenever I try a search.

**Comment by otesuji** [comment] 2021-03-05 13:31
Symbol’s function definition is void: -on in my case. can't use anymore since update!

**Comment by alphapapa** [comment] 2021-03-09 06:52
As you can see, the code in this package has not changed recently.  Can you reproduce the problem in a clean Emacs configuration?

**Comment by otesuji** [comment] 2021-03-09 09:45
Sorry but it is working again. I've updated other packages only. Strange.

**Comment by akirak** [comment] 2021-03-09 10:02
`dash-functional` was merged with `dash` and became obsolete. `-on` is now part of dash.

**Comment by falematte** [comment] 2021-03-09 11:55
I have updated melpa and dash functional. Still the same error... Any tips?

**Comment by alphapapa** [comment] 2021-03-09 23:24
> As you can see, the code in this package has not changed recently. Can you reproduce the problem in a clean Emacs configuration?

**Closed by alphapapa** 2021-03-09 23:24 UTC

**Comment by alphapapa** [comment] 2021-03-10 05:19
See also #191. You could search the closed issues for the symbol and find that issue.
