### ISSUE TITLE
Bug: org-ql-find + query-prefix lead to "Match Required" error on Vertico

### ISSUE THREAD

**Issue by danielfleischer** [alphapapa/org-ql#351] opened 2023-05-17 13:47 UTC
Run the following:

`(org-ql-find (org-agenda-files) :query-prefix "heading:")`

Get a list of completions, when trying to select something, you get "Match Required", can't complete the selection; using Vertico.

**Comment by alphapapa** [comment] 2023-05-17 23:51
Hello Daniel,

Thanks for reporting this problem, but I am unable to reproduce that behavior in a clean Emacs configuration on Emacs 28.2.  Please try to reproduce it in a clean configuration using https://github.com/alphapapa/with-emacs.sh.

Please see also other issues mentioning Vertico: https://github.com/alphapapa/org-ql/issues?q=is%3Aissue+is%3Aopen+vertico  If what you're reporting is also reported in one of them, please close this report and add your feedback there.

Thanks.

**Comment by danielfleischer** [comment] 2023-05-18 06:45
Hi, I was able to reproduce with 

1. `./with-emacs.sh -O -- -L ~/Projects/org-mode/lisp/ -l org`
2. Installing vertico, enabling it, installing org-ql.
3. Running `(org-ql-find '("myfile.org") :query-prefix "heading:")`.
4. Trying to choose something, getting "Match Required" error.

Emacs master 30, org master, vertico 1.3.

However I'm able to fix it by changing https://github.com/alphapapa/org-ql/blob/2c098540cab6a0ee7d82abe2327d524a171edd1e/org-ql-completing-read.el#L267

making the match-required nil:
```elisp
             (selected (completing-read prompt null nil nil)))
```

However I do realize this is a very complicated function, with many comments and not sure if this breaks something else.

**Comment by danielfleischer** [comment] 2023-09-14 18:40
Hi, I can confirm it's working as expected. Thanks!

**Closed** 2023-09-20 02:04 UTC
Labels: bug
