### ISSUE TITLE
Bytecomp warnining for free variable 'inherit'

### ISSUE THREAD

**Issue by alanz** [alphapapa/org-ql#307] opened 2022-10-15 09:42 UTC
A few days ago I started getting a warning on startup.  I finally got round to tracking it down (using the `advice` mechanism from https://emacs.stackexchange.com/questions/13532/warning-bytecomp-is-a-bit-vague-can-i-get-any-more-information)

```
.emacs.d/elpa/org-ql-20221007.2334/org-ql.elc:Warning: reference to free
    variable ‘inherit’
```

This is for
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0) of 2021-11-27, modified by Debian

**Comment by alphapapa** [comment] 2022-10-16 16:22
Hi Alan,

Thanks for reporting this.  When does the warning happen?

When linting byte compilation, I can't reproduce that warning on Emacs 28, which is what I mainly use, and I don't have a build of Emacs 27 handy.  Would you be able to test with Emacs 28?  (If it helps, I use Guix to easily install a newer version of Emacs locally, on top of my normal Debian/Ubuntu system, and my [with-emacs.sh](https://github.com/alphapapa/with-emacs.sh) script to keep its configuration separate.)

**Comment by alanz** [comment] 2022-10-16 17:01
The warning happens on startup.  If I do `guix shell emacs` and then run with my normal config, it does not happen (i.e. 28.1)

It happened recently, so I suspect the problem came in https://github.com/alphapapa/org-ql/commit/e54ba0102c69273183a5ffafafe878f820ab9e5f.  I will dig around  a bit later to see if I can track it down, but my money is on https://github.com/alphapapa/org-ql/commit/e54ba0102c69273183a5ffafafe878f820ab9e5f#diff-34013f28e9b645ff9d9a6dab1c4f0ca707ae51e0361da84126e8440810452773R1787

**Comment by alanz** [comment] 2022-10-16 18:53
@alphapapa using my 27.1, if I macroexpand 

```elisp
(org-ql-defpred property (property &optional value &key inherit)
 ...
)
```
(https://github.com/alphapapa/org-ql/blob/master/org-ql.el#L1732)

I get it

```elisp
(progn
  (cl-defun org-ql--predicate-property
      (property &optional value &key inherit)
   .......
  )
  (setf
   (alist-get 'property org-ql-predicates)
...
)
```
So the `setf`part is outside the `cl-defun`, so does not have the`&key inherit` in scope.

The full expansion is at https://gist.github.com/alanz/ed0294973af99a3893572df1ea4a33d6

**Comment by alphapapa** [comment] 2022-10-17 13:59
> So the `setf`part is outside the `cl-defun`, so does not have the`&key inherit` in scope.

The places in the `setf` form's value form where the symbol `inherit` is found are in `pcase` forms, in which the symbol is bound by the `pcase` macro's expansion, e.g.
```
:normalizers ,'((`(,(or 'property) ,property ,value \, plist)
```
So it's not clear to me what's causing this warning.

**Comment by alanz** [comment] 2022-10-17 18:58
I did some empirical tests today, on that function.  There are three places `inherit`appears as a variable.  If the first two are replaced with `T` the problem goes away.  I have marked them with `;; AZ` comments below

```elisp
(org-ql-defpred property (property &optional value &key inherit)
  "Return non-nil if current entry has PROPERTY (a string), and optionally VALUE (a string).
If INHERIT is nil, only match entries with PROPERTY set on the
entry; if t, also match entries with inheritance.  If INHERIT is
not specified, use the Boolean value of
`org-use-property-inheritance', which see (i.e. it is only
interpreted as nil or non-nil)."
  :normalizers ((`(,predicate-names ,property ,value . ,plist)
                 ;; Convert keyword property arguments to strings.  Non-sexp
                 ;; queries result in keyword property arguments (because to do
                 ;; otherwise would require ugly special-casing in the parsing).
                 (when (keywordp property)
                   (setf property (substring (symbol-name property) 1)))
                 (list 'property property value
                       :inherit (if (plist-member plist :inherit)
                                    (plist-get plist :inherit)
                                  org-use-property-inheritance))))
  ;; MAYBE: Should case folding be disabled for properties?  What about values?
  ;; MAYBE: Support (property) without args.

  ;; NOTE: When inheritance is enabled, the preamble can't be used,
  ;; which will make the search slower.
  :preambles ((`(,predicate-names ,property ,value . ,(map :inherit))
               ;; We do NOT return nil, because the predicate still needs to be tested,
               ;; because the regexp could match a string not inside a property drawer.

               ;; AZ: causes problem
               ;; (list :regexp (unless inherit
               (list :regexp (unless t
                               (rx-to-string `(seq bol (0+ space) ":" ,property ":"
                                                   (1+ space) ,value (0+ space) eol)))
                     :query query))
              (`(,predicate-names ,property . ,(map :inherit))
               ;; We do NOT return nil, because the predicate still needs to be tested,
               ;; because the regexp could match a string not inside a property drawer.
               ;; NOTE: The preamble only matches if there appears to be a value.
               ;; A line like ":ID: " without any other text does not match.

               ;; AZ: causes problem
               ;; (list :regexp (unless inherit
               (list :regexp (unless t
                               (rx-to-string `(seq bol (0+ space) ":" ,property ":" (1+ space)
                                                   (minimal-match (1+ not-newline)) eol)))
                     :query query)))
  :body
  (pcase property
    ('nil (user-error "Property matcher requires a PROPERTY argument"))
    (_ (pcase value
         ('nil
          ;; Check that PROPERTY exists
          (org-ql--value-at
           (point) (lambda ()
                     (org-entry-get (point) property))))
         (_
          ;; Check that PROPERTY has VALUE.

          ;; TODO: Since --value-at doesn't account for inheritance,
          ;; we should generalize --tags-at to also work for property
          ;; inheritance and use it here, which should be much faster.
          (string-equal value (org-ql--value-at
                               (point) (lambda ()
                                         ;; AZ: does not cause problem
                                         (org-entry-get (point) property inherit)))))))))
```

**Comment by ivanperez-keera** [comment] 2023-01-17 15:35
This happens for me when I try to execute `M-x org-ql-sparse-tree`, before I am prompted for a search query.

**Comment by alphapapa** [comment] 2023-03-10 10:52
AFAICT this doesn't happen on Emacs 28, which suggests to me that it was a bug in `pcase` or the byte-compiler that has been fixed.  It's probably not worth trying to address in this package for earlier Emacs versions, so I'll close this issue.  But if it presents a problem for users of earlier Emacs versions, please comment here and tag my username and I'll look at it again.

**Closed by alphapapa** 2023-03-10 10:52 UTC
