### ISSUE TITLE
Duplicate Entries on Repeated Calls to org-ql-search

### ISSUE THREAD

**Issue by georgewsinger** [alphapapa/org-ql#182] opened 2021-01-14 16:46 UTC
Repeated calls to an org-ql macro I made causes, on each call, nearly all of the entries to be duplicated in the org-ql buffer:

```elisp
(defun my-org-ql-function (files tag-name)
  (progn
    (org-ql-search files
      `(and
        (tags tag-name)
        )
      :sort '(lambda (x y)
               (string< (org-element-property :U_OVER_EST y) (org-element-property :U_OVER_EST x))
               ))
    (delete-other-windows)
    ))
```

The only way to fix the issue is to kill all of the buffers (e.g. call `spacemacs/kill-other-buffers`) and call the function afresh. The workflow that's causing this: I frequently run the same searches over and over (binded to hotkeys).

**Comment by georgewsinger** [comment] 2021-01-14 17:18
Possibly related: when I try to `org-ql-view-save` one of these views and display it later I get `Invalid Org QL query`.

**Comment by subego** [comment] 2021-07-15 02:30
Same question.

**Comment by alphapapa** [comment] 2021-07-16 10:29
Seems that I overlooked this issue for a while (it now says that it was updated yesterday, but it doesn't say what about it was).

> Repeated calls to an org-ql macro I made causes, on each call, nearly all of the entries to be duplicated in the org-ql buffer

I don't know what's going on here, but the query in the code you shared won't work as desired.  

> Possibly related: when I try to org-ql-view-save one of these views and display it later I get Invalid Org QL query.

Probably because it's not a valid query.  I recommend reading the Elisp manual sections on `defun`, `progn`, and backquoting/splicing.

I think there's no bug here, so I'm closing this.  If you can provide a reproducible test case using valid Elisp code in a clean Emacs config, please open a new issue.

**Closed by alphapapa** 2021-07-16 10:29 UTC
