### ISSUE TITLE
Installation Issue: Symbol’s function definition is void: byte-run--set-speed`

### ISSUE THREAD

**Issue by Sinthoras7** [alphapapa/org-ql#345] opened 2023-04-06 22:07 UTC
I tried to install org-ql with the following code:

`(use-package org-ql)`

Then I get the following error: `Error (use-package): org-ql/:catch: Symbol’s function definition is void: byte-run--set-speed`.

Strangely, on my other machine, the installation worked just fine. (With the same init.el) 
I have deleted and reinstalled all my packages (it took quite some time), but it did not help.

Where could this error come from? Where does the function `byte-run--set-speed` come from?

**Comment by alphapapa** [comment] 2023-04-07 08:51
I can't explain why you would get this error, but you haven't provided enough information to diagnose the problem, e.g. you haven't said what OS you're using, what version of Emacs, what version of org-ql, etc.

Note as well that `(use-package org-ql)` does not install packages by default; generally you should use `package-install` for that.

Anyway, this package doesn't refer to such a function, so the fact that you would get such a weird error suggests a problem in your Emacs installation.  Since it's not a bug in this package, I'm going to close the issue, but feel free to continue discussing it here.  Thanks.

**Closed by alphapapa** 2023-04-07 08:51 UTC

**Comment by Sinthoras7** [comment] 2023-04-07 18:12
I was not sure, that this is not a bug in this package, but you are probably right – sorry.
 
I am using the straight package manager (https://github.com/radian-software/straight.el), with the code 
```  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t) ``` 
so use-package should install it. (It also works for the other packages).

My version of emacs is emacs 27.1 and my OS on this device is PopOs.

**Comment by alphapapa** [comment] 2023-04-07 22:56
`use-package` does not install it--`straight` does.

And I'm afraid that `straight` is not something I can help you with.  Please refer to an appropriate forum or chat room.

**Comment by Sinthoras7** [comment] 2023-04-08 08:04
Thank you nevertheless :)

**Comment by alexkehayias** [comment] 2023-04-09 15:52
I also came across this—the stacktrace points to `peg` which this library depends on as of `1.0`. https://github.com/emacsmirror/peg/blob/master/peg.el#L401

For reference, I noticed this in a [GitHub CI action building org-ql with straight.el using Ubuntu and Emacs 27.2](https://github.com/alexkehayias/emacs.d/actions/runs/4650893562/jobs/8230162667).

**Comment by alphapapa** [comment] 2023-04-09 19:21
@alexkehayias Thanks.  Maybe you should report it on emacs-devel or report an Emacs bug so the peg maintainers can take a look.
