### ISSUE TITLE
Error installing org-ql with straight package manager

### ISSUE THREAD

**Issue by codygman** [alphapapa/org-ql#29] opened 2019-07-09 02:37 UTC
I have the following:

```
(use-package org-super-agenda
    :after '(org org-ql)
    :straight
    (org-super-agenda
      :type git
      :host github
      :repo "alphapapa/org-super-agenda"))

(use-package org-ql-agenda
    :after '(org org-ql)
    :straight
    (org-ql-agenda
      :type git
      :host github
      :repo "alphapapa/org-agenda-ng"
      :files ("org-ql-agenda.el")))

(use-package org-ql
    :after '(org)
    :straight
    (org-ql
      :type git
      :host github
      :repo "alphapapa/org-agenda-ng"
      :files ("org-ql.el")))
```

After evaluating that I attempt to use `org-ql-search`. After finishing the selections I get the error:

```
helm-M-x: Symbol’s value as variable is void: org-super-agenda-auto-selector-keywords
```

Any ideas?

**Comment by alphapapa** [comment] 2019-07-09 08:57
Well, `org-agenda-ng`, is not the correct repo name, but I don't know if that's the problem.

I don't use Straight, so I don't know if you're doing that correctly or idiomatically by defining `org-ql` and `org-ql-agenda` as separate packages.  I'm guessing that's not quite right, but I don't know if that's the problem.

Note that the error is related to `org-super-agenda`, not `org-ql`, and that calling the command from Helm is masking the error's source.

**Comment by akirak** [comment] 2019-08-24 09:56
I am using `org-ql` with the following configuration:

```emacs-lisp
(use-package org-ql
  :straight (org-ql :host github :repo "alphapapa/org-ql"))
```

You don't have to include `org-ql` in `:after` section of `org-super-agenda`, since `org-super-agenda` doesn't depend on `org-ql`. I use the following configuration for `org-super-agenda`:

```emacs-lisp
(use-package org-super-agenda
  :after org-agenda
  :config
  (org-super-agenda-mode 1))
```

**Comment by alphapapa** [comment] 2019-08-24 10:21
@akirak Thanks!

@codygman I think you don't need to install them as separate packages, since they're intended to be part of the `org-ql` package.  Note the distinction between Emacs "packages" and "features".  Also, note that the commands are autoloaded, so unless you're calling, from your own code, a function in `org-ql-agenda.el` that has no autoload, you shouldn't need to force it to load anyway.

Closing this since it's not a bug, but please let us know when you find the solution to using it with `straight`.

**Closed by alphapapa** 2019-08-24 10:21 UTC

**Comment by akirak** [comment] 2019-08-24 10:59
@codygman Since `org-ql` and `org-ql-agenda` are in the separate repositories, you can load `org-ql-agenda` after you install `org-ql` package with the recipe above. Nonetheless,  you might want to add the following configuration to let `straight.el` generate autoloads for `org-ql-agenda.el`:

```emacs-lisp
(use-package org-ql-agenda
  :straight org-ql)
```

That is, you can share the same recipe for a package by specifying the name in place of the recipe body.
